module.exports={
    formHead:{
       fontSize:30,
       color:"Black",
       textAlign:"center",
       fontWeight:"bold"
    },
    formInput:{
      width:"80%",
      backgroundColor:"#D2EDF0",
      
      borderRadius:10,
      marginVertical:10,
      paddingHorizontal:15,
      paddingVertical:10,
      fontSize:15
    },
    formTextLinkRight:{
        textAlign:"right",
        marginLeft:180,
        color:"gray",
        fontSize:15
    },
    formBtn:{
        width:"80%",
        backgroundColor:"#12A917",
        borderRadius:10,
        borderColor:"black",
        borderWidth:1,
        fontSize:20,
        color:"white",
        textAlign:"center",
        paddingVertical:10,
        marginVertical:10
    },
    formTextLinkCenter:{
        fontSize:15,
        color:"gray"
    },
    formHead2:{
        fontSize:20,
        textAlign:"center",
        color:"black",
        marginTop:0,
        justifyContent:"center"
    },
    formHead3:{
        fontSize:15,
        textAlign:"center",
        color:"black"
    }
}